name: Test
on:
  - pull_request
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: action/setup-node@v3
      - name: run test
        run: npm run test
  